"""Initial migration

Revision ID: ba32e778830a
Revises: 
Create Date: 2026-02-18 00:18:14.400115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba32e778830a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('min_price_pct', sa.Float(), nullable=True),
    sa.Column('max_price_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_types',
    sa.Column('type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.Column('view_probability', sa.Float(), nullable=True),
    sa.Column('cart_probability', sa.Float(), nullable=True),
    sa.Column('purchase_probability', sa.Float(), nullable=True),
    sa.Column('price_sensitivity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('type_id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Float(precision=2), nullable=False),
    sa.Column('current_price', sa.Float(precision=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('min_price', sa.Float(precision=2), nullable=True),
    sa.Column('max_price', sa.Float(precision=2), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('simulated_user_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['simulated_user_type_id'], ['user_types.type_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interactions_timestamp'), ['timestamp'], unique=False)

    op.create_table('price_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Float(precision=2), nullable=True),
    sa.Column('new_price', sa.Float(precision=2), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_histories_changed_at'), ['changed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_histories_changed_at'))

    op.drop_table('price_histories')
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interactions_timestamp'))

    op.drop_table('interactions')
    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('user_types')
    op.drop_table('categories')
    # ### end Alembic commands ###
